/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tufts-blue': '#2563eb',
        'tufts-blue-hover': '#1d4ed8',
        'smoky-black': '#0f172a',
        'background-grey': '#f1f5f9',
        'brand-white': '#ffffff',
        surface: '#ffffff',
        'surface-hover': '#f8fafc',
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"SF Pro Display"',
          '"SF Pro Text"',
          '"SF Pro Icons"',
          '"Helvetica Neue"',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        serif: ['"New York"', 'ui-serif', 'Georgia', '"Times New Roman"', 'serif'],
        mono: [
          '"SF Mono"',
          'ui-monospace',
          '"Cascadia Code"',
          '"Fira Code"',
          'Menlo',
          'Monaco',
          'Consolas',
          'monospace',
        ],
      },
      fontSize: {
        xs: ['11px', { lineHeight: '1.4' }],
        sm: ['12px', { lineHeight: '1.4' }],
        base: ['14px', { lineHeight: '1.5' }],
        md: ['15px', { lineHeight: '1.5' }],
        lg: ['17px', { lineHeight: '1.35' }],
        xl: ['20px', { lineHeight: '1.3' }],
        '2xl': ['24px', { lineHeight: '1.25' }],
        '3xl': ['28px', { lineHeight: '1.2' }],
        '4xl': ['34px', { lineHeight: '1.15' }],
        '5xl': ['48px', { lineHeight: '1.1' }],
        // Apple HIG text styles — use CSS variables so mobile overrides apply (index.css)
        caption2: ['var(--text-caption2)', { lineHeight: '1.36', letterSpacing: '0.066em' }],
        caption1: ['var(--text-caption1)', { lineHeight: '1.33', letterSpacing: '0' }],
        footnote: ['var(--text-footnote)', { lineHeight: '1.38', letterSpacing: '-0.0008em' }],
        subhead: ['var(--text-subhead)', { lineHeight: '1.4', letterSpacing: '-0.0024em' }],
        callout: ['var(--text-callout)', { lineHeight: '1.375', letterSpacing: '-0.0031em' }],
        body: ['var(--text-body)', { lineHeight: '1.47', letterSpacing: '-0.0043em' }],
        headline: ['var(--text-headline)', { lineHeight: '1.47', letterSpacing: '-0.0043em' }],
        title3: ['var(--text-title3)', { lineHeight: '1.4', letterSpacing: '0.0038em' }],
        title2: ['var(--text-title2)', { lineHeight: '1.36', letterSpacing: '0.0016em' }],
        title1: ['var(--text-title1)', { lineHeight: '1.32', letterSpacing: '0.0013em' }],
        large: ['var(--text-large)', { lineHeight: '1.21', letterSpacing: '0.0037em' }],
        hero: ['var(--text-hero)', { lineHeight: '1.14', letterSpacing: '-0.003em' }],
      },
      letterSpacing: {
        tighter: '-0.02em',
        tight: '-0.01em',
        normal: '0',
        wide: '0.04em',
        wider: '0.08em',
        'apple-tightest': '-0.0043em',
        'apple-tight': '-0.0024em',
        'apple-normal': '0',
        'apple-wide': '0.004em',
        'apple-wider': '0.066em',
      },
      boxShadow: {
        card: '0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.06)',
        'card-hover': '0 4px 6px -1px rgb(0 0 0 / 0.08), 0 2px 4px -2px rgb(0 0 0 / 0.06)',
        soft: '0 2px 8px rgb(0 0 0 / 0.06)',
        'bottom-nav': '0 -2px 10px rgb(0 0 0 / 0.08)',
      },
      borderRadius: {
        xl: '0.75rem',
        '2xl': '1rem',
      },
      spacing: {
        'safe-top': 'env(safe-area-inset-top)',
        'safe-bottom': 'env(safe-area-inset-bottom)',
        'safe-left': 'env(safe-area-inset-left)',
        'safe-right': 'env(safe-area-inset-right)',
        'touch': '2.75rem', // ~44px min touch target
      },
      minHeight: {
        touch: '2.75rem',
      },
      maxWidth: {
        'app': '90rem',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
